site:
  name: Sample website
  locale: en
  meta_keywords: some meta keywords
  meta_description: some meta description
  pages:
  - index:
      title: Home page
  - about_us:
      title: About us
  - music:
  - store:
      redirect_url: http://www.apple.com/fr/itunes/
  - contact:
      title: Contact us
  - "404":
      title: Page not found
  content_types:
    events:
      name: Events
      description: List of upcoming events
      slug: events
      order_by: created_at
      highlighted_field_name: place
      api_enabled: false
      fields:
      - place:
          hint: Name of the place
      - date:
          kind: date
          hint: Date of the event
      - city:
          kind: string
          label: City of the event
      - state:
          kind: string
          label: State of the event
      contents:
      - Avogadro's Number:
          date: 2010/06/11
          city: Fort Collins
          state: Colorado
      - Quixote's True Blue:
          date: 2010/06/10
          city: Denver
          state: Colorado
      - Kelly's Westport Inn:
          date: 2010/06/06
          city: Kansas City
          state: Missouri
      - Browne's Market:
          date: 2010/06/06
          city: Kansas City
          state: Missouri
      - Ballydoyle's:
          date: 2010/06/05
          city: Aurora
          state: Illinois
      - The Belmont:
          date: 2010/06/04
          city: Hamtramk
          state: Michigan
      - Avogadro's Number:
          date: 2009/06/11
          city: Fort Collins
          state: Colorado
      - Quixote's True Blue:
          date: 2009/06/10
          city: Denver
          state: Colorado
      - Kelly's Westport Inn:
          date: 2009/06/06
          city: Kansas City
          state: Missouri
      - Browne's Market:
          date: 2009/06/06
          city: Kansas City
          state: Missouri
      - Ballydoyle's:
          date: 2009/06/05
          city: Aurora
          state: Illinois
      - The Belmont:
          date: 2009/06/04
          city: Hamtramk
          state: Michigan
    messages:
      name: Messages
      description: Messages posted by new potential customers
      slug: messages
      highlighted_field_name: name
      api_enabled: true
      order_by: date
      fields:
      - name:
          hint: Full name
      - email:
          hint: Email
      - message:
          hint: Customer message
          kind: text
    songs:
      name: Songs
      highlighted_field_name: title
      order_by: manually
      slug: songs
      fields:
      - title:
          kind: string
          required: true
          hint: Title of your song
      - cover:
          label: Cover
          kind: file
          required: true
      - short_description:
          kind: text
      - audio_url:
          kind: string
          hint: Url to a service like Blip for instance
      - duration:
          hint: "format like: mm:ss"
      contents:
      - "Song #1":
          duration: "6:28"
          short_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae tincidunt urna. Nunc felis purus, ultricies et venenatis bibendum, fringilla eu lectus. Sed cursus, sem at blandit mattis, libero quam egestas tortor, eget cursus dolor tellus id nunc.
          audio_url: http://blip.tv/file/get/NicolasRaynier-Milk617.flv
          cover: /samples/asset_collections/cover.jpg
      - "Song #2":
          duration: "6:28"
          short_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae tincidunt urna. Nunc felis purus, ultricies et venenatis bibendum, fringilla eu lectus. Sed cursus, sem at blandit mattis, libero quam egestas tortor, eget cursus dolor tellus id nunc.
          audio_url: http://blip.tv/file/get/NicolasRaynier-Milk617.flv
          cover: /samples/asset_collections/cover.jpg
      - "Song #3":
          duration: "6:28"
          short_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae tincidunt urna. Nunc felis purus, ultricies et venenatis bibendum, fringilla eu lectus. Sed cursus, sem at blandit mattis, libero quam egestas tortor, eget cursus dolor tellus id nunc.
          audio_url: http://blip.tv/file/get/NicolasRaynier-Milk617.flv
          cover: /samples/asset_collections/cover.jpg
      - "Song #4":
          duration: "6:28"
          short_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae tincidunt urna. Nunc felis purus, ultricies et venenatis bibendum, fringilla eu lectus. Sed cursus, sem at blandit mattis, libero quam egestas tortor, eget cursus dolor tellus id nunc.
          audio_url: http://blip.tv/file/get/NicolasRaynier-Milk617.flv
          cover: /samples/asset_collections/cover.jpg
      - "Song #5":
          duration: "6:28"
          short_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae tincidunt urna. Nunc felis purus, ultricies et venenatis bibendum, fringilla eu lectus. Sed cursus, sem at blandit mattis, libero quam egestas tortor, eget cursus dolor tellus id nunc.
          audio_url: http://blip.tv/file/get/NicolasRaynier-Milk617.flv
          cover: /samples/asset_collections/cover.jpg
      - "Song #6":
          duration: "6:28"
          short_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae tincidunt urna. Nunc felis purus, ultricies et venenatis bibendum, fringilla eu lectus. Sed cursus, sem at blandit mattis, libero quam egestas tortor, eget cursus dolor tellus id nunc.
          audio_url: http://blip.tv/file/get/NicolasRaynier-Milk617.flv
          cover: /samples/asset_collections/cover.jpg
      - "Song #7":
          duration: "6:28"
          short_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae tincidunt urna. Nunc felis purus, ultricies et venenatis bibendum, fringilla eu lectus. Sed cursus, sem at blandit mattis, libero quam egestas tortor, eget cursus dolor tellus id nunc.
          audio_url: http://blip.tv/file/get/NicolasRaynier-Milk617.flv
          cover: /samples/asset_collections/cover.jpg
      - "Song #8":
          duration: "6:28"
          short_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vitae tincidunt urna. Nunc felis purus, ultricies et venenatis bibendum, fringilla eu lectus. Sed cursus, sem at blandit mattis, libero quam egestas tortor, eget cursus dolor tellus id nunc.
          audio_url: http://blip.tv/file/get/NicolasRaynier-Milk617.flv
          cover: /samples/asset_collections/cover.jpg
    updates:
      name: Updates
      description: List of updates
      slug: updates
      order_by: created_at
      highlighted_field_name: title
      api_enabled: false
      fields:
      - title:
          hint: Not displayed in the website
      - text:
          kind: text
          hint: Text displayed in the home page
      - date:
          kind: date
          hint: Date of the update
      contents:
      - "Update #6":
          text: john posted a new post
          date: 2009/11/16
      - "Update #5":
          text: brian posted a new post
          date: 2009/11/02
      - "Update #4":
          text: NEW ALBUM FINISHED!!
          date: 2009/10/09
      - "Update #3":
          text: site redesign
          date: 2009/06/29
      - "Update #2":
          text: added a chatroom
          date: 2009/05/23
      - "Update #1":
          text: added some free stuff
          date: 2009/05/12