# TODO: explain it
name: demo_effe

# TODO: explain it
# subdomain: sample

# TODO: explain it
# domains: [www.example.com, example.com]

# TODO: explain it
locales: [en]

# TODO: explain it
seo_title: demo_effe
meta_keywords: "some meta keywords"
meta_description: "some meta description"